# Site settings
title: Qingzhi(Chellie) You, Game Developer
email: youqingzhi1@gmail.com
description: > # keep this and put description below
  Programmer and Designer
url: "https://chelliy.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/qingzhi-you-b6b267223/"
github_username: chelliy
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
